const ApiEndpoints = {
  VERIFY_OTP: '/auth/verify-otp',
  WALLET_INFO: '/wallet',
  QR_CODE_GENERATOR: '/qr-code',
  FETCH_IMAGES: '/slider-images',
  FETCH_WALLET_SUMMARY: '/wallets/summery',
  FETCH_INVOICE_SUMMARY: '/invoices/summary',
  OFFERS: '/offers?page=:pageNumber',
  FETCH_INVOICE_LIST: '/invoices?page=:pageNumber',
  FETCH_INVOICE_DETAIL: '/invoices/:id/details',
  UPDATE_CONTACT: '/contacts',
  CLIENTS: '/clients',
  REWARD_REQUESTS: '/reward-requests/transactions?page=:pageNumber',
  UPLOAD_INVOICE: '/invoices',
  OFFERS_LIST: '/products/offers',
  GENERATE_OTP: '/otp/generate',
  REDEEM_REQUEST: '/reward-requests',
  COUPON_PARTNERS: '/rewards/forOrganization/:id',
  AUTHORIZED_STOCKISTS: '/channel-partners/stockist?page=:pageNumber',
  NOTIFICATIONS: '/notifications',
  ORDERS: '/orders?page=:pageNumber',
  CHANGE_ORDER_STATUS: '/orders/consent/:uuid/:status',
  ORDER_SERVICE: '/orders/service?page=:pageNumber',
  TRACK_ORDER: '/orders/:orderId/track-order/:subOrderId',
  FETCH_IDENTITY: '/identity/validate/:identityType/:value',
  REGISTER_USER: '/channel-partners/register',
  CHANNEL_PARTNER_TYPES: '/channel-partners/types',
  FETCH_DIVISIONS: '/organizations',
  ORDERS_SUMMARY: '/orders/list/for-customer',
};

export default ApiEndpoints;
