export default {
  caughtUp: "You're all caught up!",
  validMobile: 'Number must be 10 digit and starts from 6-9.',
  enterMobile: 'New Mobile Number',
  enterValidNumber: 'Please enter a valid number',
  yes: 'Yes',
  no: 'No',
  edit: 'Edit',
  save: 'Save',
  goToDashboard: 'Go to Dashboard',
  done: 'Done',
  viewAll: 'View All',
  submit: 'Submit',
  continue: 'Continue',
  dimiss: 'Dismiss',
  proceed: 'Proceed',
  allow: 'Allow',
  notYetProcessed: 'Not yet Processed',
  somethingWrong: 'Something went wrong',
  na: 'N/A',
  alert: {
    logout: 'Do you want to logout?',
  },
  Organisations: {
    name: 'Organisations',
    brands: 'Brands',
    stockists: 'Stockists',
  },
  search: {
    search: 'Search',
    enterDepartmentName: 'Enter Invoice ID',
    enterProductName: 'Product Name',
    enterName: 'Search By Name',
  },
  reviewStatus: {
    approved: 'Approved',
    rejected: 'Rejected',
    pending: 'Pending',
    notEligible: 'Not Eligible',
  },
  profile: {
    appVersion: 'App Version: ',
    profile: 'Profile',
    businessName: 'Business Name:',
    mobileNo: 'Mobile No.:',
    dlNo: 'D/L No.:',
    panNo: 'PAN No.:',
    gstNo: 'GST No.:',
    personalDetails: 'Personal Details',
    businessDetails: 'Business Details',
    emailId: 'Email Id:',
    whatsAppNo: 'WhatsApp No.:',
    address: 'Address',
    updated: {
      mobile: 'Mobile number successfully updated',
      whatsapp: 'WhatsApp successfully updated',
    },
  },
  filter: {
    filter: 'Filter',
    reedemSuccessful: 'Redeem Request Successful',
    reedemSummary: 'Redeem Summary',
    clearAllFilter: 'Clear All',
    applyFilters: 'Apply',
    organisation: 'Organisation',
    filters: 'Filters',
    amountRange: 'Amount\nRange',
    timeline: 'Timeline',
    approvedPointsRange: 'Approved Points Range',
    rewardPointsRange: 'Reward Points Range',
    invoiceStatus: 'Invoice status',
    invoiceStatusValues: ['Approved', 'Rejected', 'Pending'],
    timeLineValues: [
      'Last 30 Days',
      'Last 3 months',
      'Last 12 months',
      'Last 24 months',
    ],
    reedemStatus: 'Redeem status',
    reedemStatusValue: ['Approved', 'Processing'],
    transaction: 'Transaction',
    transactionValues: ['Debit', 'Credit'],
  },
  contactRep: {
    contactRep: 'Contact Reps',
  },
  notification: {
    notification: 'Notification',
    All: 'All',
    Invoices: 'Invoices',
    Wallet: 'Wallet',
    MyGoal: 'My Goal',
  },
  invoice: {
    help: 'Help',
    uploadOn: 'Uploaded On',
    invoiceUpload: 'Invoice Upload',
    myUploads: 'My uploads',
    addPages: 'Add Pages',
    invoiceOverview: 'Invoice Overview',
    invoiceList: 'Invoice List',
    approved: 'Approved',
    rejected: 'Rejected',
    pending: 'Pending',
    invoiceText: 'Invoice',
    rewardPoints: 'Reward Points',
    uploaded: 'Invoice successfully uploaded',
    notUploaded: 'Unable to upload invoice',
  },
  subscription: {
    successSubscription: 'Subscription Request Successful',
    successSubscriptionInfo:
      'Your organization has request been updated. Your request will be processed in few days.',
    subscribe: 'Subscribe',
    mySubscription: 'My Subscriptions',
    subscription: 'Subscriptions',
    newSubscription: 'New Subscriptions',
    moreInfo: 'More Info',
    upload: 'Upload',
    organisationDetails: 'Organisation details',
    Brands: 'Brands',
    Stockist: 'Stockist',
  },
  stockist: {
    stockist: 'Stockists',
    authrisedStockist: 'Authorised Stockist',
  },
  QRCodePopup: {
    info: 'Your QR code is private & confidential. Please show this code with the officia GoApptive or Company Reps with whom you would like to share your channel paisa transactions.',
    codeExpire: 'Code expires in ',
    regenerate: 'Regenerate',
    codeExpired: 'Qr Code Expired',
  },
  drawer: {
    termsConditions: 'Terms & Conditions',
    aboutChannelPaisa: 'About Channel Paisa',
    logout: 'Logout',
  },
  location: {
    locationRequired: 'Location Permission Required',
    locationInfo:
      'Channel Paisa collects location data to improve customer reach. Kindly allow location access.',
    somethingWrong:
      'Something went wrong! Please make sure that location permissions are allowed',
  },
  auth: {
    registrationSuccess: 'Registration Successful!',
    help: 'Help?',
    loginWithMobile: 'Login with Mobile No.',
    register: 'Register',
    login: 'Login',
    enterMobileNo: 'Enter mobile no.',
    mobileNo: 'Mobile No.',
    getOTP: 'Get OTP',
    termsAndConditions: 'Terms & Conditions',
    enterOTP: 'Enter OTP',
    requestOTPIn: 'Resend OTP in ',
    or: 'OR',
    dontReceiveOTP: 'Didn’t Receive OTP? ',
    requestOn: 'Request on',
    sms: 'SMS',
    whatsApp: 'Whatsapp',
    call: 'Call',
    enterDetails: 'Enter Details',
    enterGSTDetails: 'Enter GST Details',
    enterPANDetails: 'Enter PAN Details',
    enterDLNo: 'Enter Drug Licence Number',
    enterGSTNumber: 'GST No.',
    enterLicenseNumber: 'DL Number',
    enterPANNumber: 'PAN No.',
    dontHaveGST: 'I don’t have GST number',
    dontHavePAN: 'I don’t have PAN number',
    confirmYourDetails: 'Confirm your Details',
    enterOwnerName: 'Enter Owner Name',
    enterShopName: 'Enter Shop Name',
    enterAddress: 'Enter Address',
    enterPincode: 'Enter Pincode',
    documentUpload: 'Document Upload',
    uploadBanner: 'Upload Banner',
    attachFile: 'Attach a file',
    attachBanner: 'Attach payment receipts, bills etc.',
    uploadLetterHead: 'Upload Letterhead',
    attachLetterHead: 'Attach payment receipts, bills etc.',
    uploadingFile: 'Uploading file',
    uploadedOn: 'Uploaded On',
    upload: 'Upload',
    chooseOrganisation: 'Choose Organisation',
    choosePaymentReceipts: 'Attach payment receipts, bills etc.',
  },
  tab: {
    dashboard: 'Dashboard',
    offers: 'Offers',
    wallet: 'Wallet',
    invoice: 'Invoice',
  },
  offer: {
    enterQuantity: 'Enter Quantity',
    pointsPerUnit: 'Points per unit: ',
    total: 'Total',
    points: 'Points',
    calculatePoints: 'Calculate Points',
    noOffersFound: 'No offers found',
  },
  dashboard: {
    prioritynoti: 'Priority notifications',
    viewall: 'View All',
    kycpending: 'Your KYC is pending',
    targetachi: 'Target achieved',
    offerover: 'Offer overview',
    walletover: 'Wallet Overview',
    gotowallet: 'Go to wallet',
    redeemablepoints: 'Redeemable Points',
    pendingpoints: 'Pending Points',
    currenearning: 'Current month earning',
    lastearning: 'Last month earning',
    target: 'Target',
    suggestions: 'Suggestions',
    youproductx: 'You can buy 50 quantities of Product X',
  },

  wallet: {
    selectDivision: 'Select Division',
    selectCompany: 'Select company to redeem points',
    redeemPoints: 'Redeem Points',
    pointRecive: 'Total Points Redeemed',
    pendingPoint: 'Pending Points',
    redeemablePoints: 'Redeemable Points',
    redeemNow: 'Redeem Now',
    redeemForPoint: 'Redeem for 250 Points',
    allTransactions: 'All Transactions',
    couponsCode: 'GoRupi Coupons',
    dismissX: 'Dismiss X',
    redeemRequestNo: 'Redeem Request No.',
    viewCoupon: 'View Coupon',
  },
  errors: {
    somethingWrong: 'Something went wrong. Please try again after sometime',
  },
  otpSent: 'OTP sent successfully',
  noData: 'No data',
};
